### ISSUE TITLE
Articulation Data Generation using SAPEIN 

### ISSUE THREAD

**Issue by FeiiYin** [zubair-irshad/articulated-object-nerf#10]
Hi, Thanks for your awesome work.
I want to synthesize data of articulation objects using SAPEIN of various states. (i.e., After rotation or translation)
However, I have not found any clue from the documentation of SAPEIN.
Can you provide several tips or short codes to insight me? 
That will be very helpful to me! Thanks in advance.

**Comment by zubair-irshad** [comment]
Thanks for your question. Does the [recent commit](https://github.com/zubair-irshad/articulated-object-nerf/pull/6) answer your question? I would try the [data generation](https://github.com/zubair-irshad/articulated-object-nerf#-dataset) scripts mentioned here and see if they are useful to your use case.

**Comment by FeiiYin** [comment]
I have checked the script. But I would like to know hot to explicitly control the state. For example, if I want to rotate the scissors in the range of 10, 20, 30, 40, 50 degree and render the images respectively, which parameters should I change?

**Comment by FeiiYin** [comment]
I have checked the file again, where the args `q_pos` can be used to change the status. The script need to be made with small adaptations. Thanks!

**Comment by zubair-irshad** [comment]
That's correct. If you are generating data for multiple instances, make sure to account for the `q_pos` for all instances not starting from 0th degree. You could look at the starting and ending states in the URDF file. if you end up implementing this, please feel free to also submit a PR.
