### ISSUE TITLE
Duplicate links

### ISSUE THREAD

**Issue by sloanr** [zubair-irshad/articulated-object-nerf#2]
Current:
> This repository is the experimental implementation of articulated object NeRF training and rendering from some of the ideas mentioned in a few papers including [CLA-NeRF](https://arxiv.org/abs/2202.00181) and [NASAM]~(https://arxiv.org/abs/2202.00181)~.

The CLA-NeRF arXiv is actually linked twice.

```suggestion
[NASAM](https://arxiv.org/abs/2205.08525)
```

**Comment by zubair-irshad** [comment]
Thanks for mentioning. I corrected the link!
