### ISSUE TITLE
Question on data generation for stage 1

### ISSUE THREAD

**Issue by DJNing** [zubair-irshad/articulated-object-nerf#3]
Thanks for your great work on reproducing CLA-NeRF!

Since the data generation code has not been release yet. I am trying to write the generation code myself. And I am getting some questions on this. It would be helpful if you could give me some hint on this.

1. **Defining camera_angle_x**

I saw related code for ```camera_angle_x``` in the [dataloader](https://github.com/zubair-irshad/articulated-object-nerf/blob/863c6ade6283d682404bc6e5d75fc516d413b05b/datasets/sapien.py#L61). But I am not sure why we need to define that as we can get focal length directly from the Sapien library. Would it be OK if I just use that focal length? 

Another minor issue is that it seems the image resolution is hard coded in the dataloader.

2. **How to save the c2w matrix**

In the Sapien library, there are several methods for camera position e.g., ```camera.get_model_matrix()```, ```camera.pose.to_transformation_matrix()```, ```camera.get_extrinsic_matrix()```. I am not sure which is used in this repo. 

Thank you very much for your reply!

**Comment by zubair-irshad** [comment]
Thank you for your interest in this repo. 

1. Yes you could use focal length directly. The motivation for saving it in this format is to make it compatible with the original NeRF's `transforms.json` format i.e. the [NeRF blender dataset](https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1). 

2. We directly save poses using `camera.get_model_matrix()` which is OpenGL camera convention.
