### ISSUE TITLE
Requirement fix

### ISSUE THREAD

**Issue by DJNing** [zubair-irshad/articulated-object-nerf#5]
The **vren** package used [here](https://github.com/zubair-irshad/articulated-object-nerf/blob/863c6ade6283d682404bc6e5d75fc516d413b05b/models/vanilla_nerf/helper.py#L29) is not installed with requirements.txt. 

And I've searched on python pip but failed to locate such package. Would you mind telling me how to install it?

**Comment by zubair-irshad** [comment]
We don't need vren or AABB intersection in our codebase since this was part of some of our earlier experiments. I ave removed this in the latest commit. Thank you!
